import 'dart:math' as math;
import '../models/subject_attendance.dart';

/// Categories of smart insights generated by the deterministic engine.
enum InsightCategory {
  recovery,
  leavePlanning,
  futurePredictions,
  subjectAnalysis,
  streaks,
  warnings,
  celebrations,
}

/// A single dynamic insight / question card.
class SmartInsightCard {
  const SmartInsightCard({
    required this.id,
    required this.category,
    required this.question,
    required this.answer,
    required this.iconName,
    required this.severity, // 'normal', 'warning', 'danger', 'success'
    this.subjectName,
    this.actionLabel,
    this.actionRoute,
  });

  final String id;
  final InsightCategory category;
  final String question;
  final String answer;
  final String iconName;
  final String severity; // 'normal', 'warning', 'danger', 'success'
  final String? subjectName;
  final String? actionLabel;
  final String? actionRoute;
}

/// Comprehensive analysis summary returned by the offline engine.
class AttendanceAnalysisReport {
  const AttendanceAnalysisReport({
    required this.overallPercentage,
    required this.totalHeld,
    required this.totalAttended,
    required this.totalMissed,
    required this.targetPercentage,
    required this.isOverallSafe,
    required this.totalSafeBunks,
    required this.totalClassesToRecover,
    required this.highestSubject,
    required this.lowestSubject,
    required this.subjectsBelowTarget,
    required this.subjectsAboveTarget,
    required this.cards,
  });

  final double overallPercentage;
  final int totalHeld;
  final int totalAttended;
  final int totalMissed;
  final double targetPercentage;
  final bool isOverallSafe;
  final int totalSafeBunks;
  final int totalClassesToRecover;
  final SubjectAttendance? highestSubject;
  final SubjectAttendance? lowestSubject;
  final List<SubjectAttendance> subjectsBelowTarget;
  final List<SubjectAttendance> subjectsAboveTarget;
  final List<SmartInsightCard> cards;
}

/// Pure rule-based, offline mathematical attendance engine for ScholarSync.
/// All calculations are deterministic, instant, and require no internet or AI API.
class SmartAttendanceInsightsEngine {
  const SmartAttendanceInsightsEngine._();

  // ── Mathematical Formulas ──────────────────────────────────────────────────

  /// Standard percentage calculation: (attended / held) * 100
  /// Guards against division by zero and negative values.
  static double calculatePercentage(int attended, int held) {
    if (held <= 0) return 100.0;
    final clampedAttended = math.max(0, math.min(attended, held));
    final pct = (clampedAttended / held) * 100.0;
    return double.parse(pct.toStringAsFixed(1));
  }

  /// Number of consecutive classes student must attend to reach [targetPct].
  /// Formula: ceil((target * held - 100 * attended) / (100 - target))
  static int classesToReachTarget({
    required int attended,
    required int held,
    required double targetPct,
  }) {
    if (targetPct >= 100.0) {
      if (attended == held && held > 0) return 0;
      return 999; // Practically unattainable if any class missed
    }
    if (held <= 0) return 0;
    final currentPct = (attended / held) * 100.0;
    if (currentPct >= targetPct) return 0;

    final numerator = (targetPct * held) - (100.0 * attended);
    final denominator = 100.0 - targetPct;
    if (denominator <= 0) return 999;

    final req = (numerator / denominator).ceil();
    return math.max(0, req);
  }

  /// Number of classes a student can safely miss before dropping below [targetPct].
  /// Formula: floor((100 * attended - target * held) / target)
  static int safeBunksAvailable({
    required int attended,
    required int held,
    required double targetPct,
  }) {
    if (targetPct <= 0.0) return 999;
    if (held <= 0) return 0;
    final currentPct = (attended / held) * 100.0;
    if (currentPct < targetPct) return 0;

    final numerator = (100.0 * attended) - (targetPct * held);
    final bunks = (numerator / targetPct).floor();
    return math.max(0, bunks);
  }

  /// Simulates what the percentage will become if student attends next [attend]
  /// and skips next [skip] classes.
  static double simulateFuturePercentage({
    required int currentAttended,
    required int currentHeld,
    required int attend,
    required int skip,
  }) {
    final newAttended = currentAttended + attend;
    final newHeld = currentHeld + attend + skip;
    return calculatePercentage(newAttended, newHeld);
  }

  // ── Engine Analysis & Card Generation ──────────────────────────────────────

  /// Analyzes a list of subject attendances against a specified [targetPct]
  /// and generates deterministic, human-friendly insight cards.
  static AttendanceAnalysisReport generateReport({
    required List<SubjectAttendance> subjects,
    double targetPct = 75.0,
  }) {
    int totalHeld = 0;
    int totalAttended = 0;

    for (final s in subjects) {
      totalHeld += s.totalClasses;
      totalAttended += s.attendedClasses;
    }

    final totalMissed = math.max(0, totalHeld - totalAttended);
    final overallPct = calculatePercentage(totalAttended, totalHeld);
    final isOverallSafe = overallPct >= targetPct;

    final subjectsBelow = <SubjectAttendance>[];
    final subjectsAbove = <SubjectAttendance>[];

    SubjectAttendance? highestSub;
    SubjectAttendance? lowestSub;
    double maxPct = -1.0;
    double minPct = 101.0;

    int totalSafeBunks = 0;
    int totalRecoverNeeded = 0;

    for (final s in subjects) {
      final p = s.totalClasses > 0
          ? (s.attendedClasses / s.totalClasses) * 100.0
          : 100.0;

      if (p < targetPct) {
        subjectsBelow.add(s);
        totalRecoverNeeded += classesToReachTarget(
          attended: s.attendedClasses,
          held: s.totalClasses,
          targetPct: targetPct,
        );
      } else {
        subjectsAbove.add(s);
        totalSafeBunks += safeBunksAvailable(
          attended: s.attendedClasses,
          held: s.totalClasses,
          targetPct: targetPct,
        );
      }

      if (s.totalClasses > 0) {
        if (p > maxPct) {
          maxPct = p;
          highestSub = s;
        }
        if (p < minPct) {
          minPct = p;
          lowestSub = s;
        }
      }
    }

    final cards = <SmartInsightCard>[];

    if (subjects.isEmpty) {
      cards.add(
        const SmartInsightCard(
          id: 'empty_tracker',
          category: InsightCategory.subjectAnalysis,
          question: 'No subjects tracked yet',
          answer: 'Add your semester subjects to unlock instant attendance recovery insights, safe bunk calculations, and future predictions.',
          iconName: 'info_outline',
          severity: 'normal',
          actionLabel: 'Add Subject',
        ),
      );
      return AttendanceAnalysisReport(
        overallPercentage: 100.0,
        totalHeld: 0,
        totalAttended: 0,
        totalMissed: 0,
        targetPercentage: targetPct,
        isOverallSafe: true,
        totalSafeBunks: 0,
        totalClassesToRecover: 0,
        highestSubject: null,
        lowestSubject: null,
        subjectsBelowTarget: const [],
        subjectsAboveTarget: const [],
        cards: cards,
      );
    }

    // ── 1. Smart Warnings & Celebrations ────────────────────────────────────
    if (subjectsBelow.isNotEmpty) {
      for (final s in subjectsBelow) {
        final req = classesToReachTarget(
          attended: s.attendedClasses,
          held: s.totalClasses,
          targetPct: targetPct,
        );
        final pctVal = s.totalClasses > 0
            ? (s.attendedClasses / s.totalClasses * 100).toStringAsFixed(1)
            : '0.0';
        final pctStr = '$pctVal%';

        cards.add(
          SmartInsightCard(
            id: 'warning_${s.id}',
            category: InsightCategory.warnings,
            question: '⚠️ ${s.subjectName} is below target ($pctStr)',
            answer: 'You are currently below your safe threshold of ${targetPct.toInt()}%. You must attend the next $req consecutive lecture${req == 1 ? '' : 's'} to recover.',
            iconName: 'warning_amber_rounded',
            severity: 'danger',
            subjectName: s.subjectName,
            actionLabel: 'View Timetable',
          ),
        );
      }
    } else if (overallPct >= 95.0) {
      cards.add(
        SmartInsightCard(
          id: 'celebration_elite',
          category: InsightCategory.celebrations,
          question: '🌟 Elite Attendance (${overallPct.toStringAsFixed(1)}%)',
          answer: 'Outstanding consistency! All subjects are safely above your ${targetPct.toInt()}% target with $totalSafeBunks total bunks available across your courses.',
          iconName: 'workspace_premium_rounded',
          severity: 'success',
        ),
      );
    }

    // ── 2. Recovery Questions (Dynamic: only if subjects need recovery) ──────
    if (subjectsBelow.isNotEmpty) {
      // Urgent subject
      subjectsBelow.sort((a, b) {
        final reqA = classesToReachTarget(
          attended: a.attendedClasses,
          held: a.totalClasses,
          targetPct: targetPct,
        );
        final reqB = classesToReachTarget(
          attended: b.attendedClasses,
          held: b.totalClasses,
          targetPct: targetPct,
        );
        return reqB.compareTo(reqA); // most needed first
      });

      final mostUrgent = subjectsBelow.first;
      final urgentReq = classesToReachTarget(
        attended: mostUrgent.attendedClasses,
        held: mostUrgent.totalClasses,
        targetPct: targetPct,
      );

      cards.add(
        SmartInsightCard(
          id: 'recovery_urgent_subject',
          category: InsightCategory.recovery,
          question: 'Which subject needs immediate attention?',
          answer: '${mostUrgent.subjectName} currently requires the most attention. You need to attend the next $urgentReq classes without skipping.',
          iconName: 'crisis_alert_rounded',
          severity: 'danger',
          subjectName: mostUrgent.subjectName,
        ),
      );

      // Closest to recovery
      final closest = subjectsBelow.last;
      final closestReq = classesToReachTarget(
        attended: closest.attendedClasses,
        held: closest.totalClasses,
        targetPct: targetPct,
      );

      cards.add(
        SmartInsightCard(
          id: 'recovery_closest_subject',
          category: InsightCategory.recovery,
          question: 'Which subject is closest to recovery?',
          answer: '${closest.subjectName} is closest to safety. Attending just $closestReq more lecture${closestReq == 1 ? '' : 's'} will bring it back above ${targetPct.toInt()}%.',
          iconName: 'trending_up_rounded',
          severity: 'warning',
          subjectName: closest.subjectName,
        ),
      );

      cards.add(
        SmartInsightCard(
          id: 'recovery_total_classes',
          category: InsightCategory.recovery,
          question: 'How many total lectures do I need to attend to reach my target?',
          answer: 'You need to attend a combined total of $totalRecoverNeeded classes across ${subjectsBelow.length} subject${subjectsBelow.length == 1 ? '' : 's'} to meet your ${targetPct.toInt()}% safe target.',
          iconName: 'flag_rounded',
          severity: 'warning',
        ),
      );
    }

    // ── 3. Leave Planning ────────────────────────────────────────────────────
    if (subjectsAbove.isNotEmpty) {
      subjectsAbove.sort((a, b) {
        final bA = safeBunksAvailable(
          attended: a.attendedClasses,
          held: a.totalClasses,
          targetPct: targetPct,
        );
        final bB = safeBunksAvailable(
          attended: b.attendedClasses,
          held: b.totalClasses,
          targetPct: targetPct,
        );
        return bB.compareTo(bA); // most safe bunks first
      });

      final bestBunkSub = subjectsAbove.first;
      final maxBunks = safeBunksAvailable(
        attended: bestBunkSub.attendedClasses,
        held: bestBunkSub.totalClasses,
        targetPct: targetPct,
      );

      cards.add(
        SmartInsightCard(
          id: 'leave_max_bunks',
          category: InsightCategory.leavePlanning,
          question: 'How many lectures can I safely miss?',
          answer: 'You can safely miss $totalSafeBunks lecture${totalSafeBunks == 1 ? '' : 's'} across all subjects. ${bestBunkSub.subjectName} has the largest buffer with $maxBunks safe bunks.',
          iconName: 'event_busy_rounded',
          severity: 'normal',
        ),
      );
    }

    // Leave next class check for overall / lowest safe
    if (lowestSub != null && lowestSub.totalClasses > 0) {
      final ifSkipNext = simulateFuturePercentage(
        currentAttended: lowestSub.attendedClasses,
        currentHeld: lowestSub.totalClasses,
        attend: 0,
        skip: 1,
      );
      final willDrop = ifSkipNext < targetPct;

      cards.add(
        SmartInsightCard(
          id: 'leave_miss_next',
          category: InsightCategory.leavePlanning,
          question: 'Can I miss the next ${lowestSub.subjectName} lecture?',
          answer: willDrop
              ? 'No — missing the next lecture will drop your ${lowestSub.subjectName} attendance to ${ifSkipNext.toStringAsFixed(1)}%, which is below your ${targetPct.toInt()}% threshold.'
              : 'Yes — skipping the next lecture will make your attendance ${ifSkipNext.toStringAsFixed(1)}%, which remains above your safe target of ${targetPct.toInt()}%.',
          iconName: willDrop ? 'block_rounded' : 'check_circle_outline_rounded',
          severity: willDrop ? 'danger' : 'success',
          subjectName: lowestSub.subjectName,
        ),
      );
    }

    // ── 4. Future Predictions ────────────────────────────────────────────────
    if (lowestSub != null && lowestSub.totalClasses > 0) {
      final attendNext1 = simulateFuturePercentage(
        currentAttended: lowestSub.attendedClasses,
        currentHeld: lowestSub.totalClasses,
        attend: 1,
        skip: 0,
      );
      final attendNext3 = simulateFuturePercentage(
        currentAttended: lowestSub.attendedClasses,
        currentHeld: lowestSub.totalClasses,
        attend: 3,
        skip: 0,
      );
      final skipNext3 = simulateFuturePercentage(
        currentAttended: lowestSub.attendedClasses,
        currentHeld: lowestSub.totalClasses,
        attend: 0,
        skip: 3,
      );

      cards.add(
        SmartInsightCard(
          id: 'future_prediction_next_3',
          category: InsightCategory.futurePredictions,
          question: 'What happens to ${lowestSub.subjectName} if I attend or miss the next 3 lectures?',
          answer: '• Attending next 3: jumps to ${attendNext3.toStringAsFixed(1)}% (+${(attendNext3 - calculatePercentage(lowestSub.attendedClasses, lowestSub.totalClasses)).toStringAsFixed(1)}%)\n• Missing next 3: drops to ${skipNext3.toStringAsFixed(1)}%\n• Attending next 1: reaches ${attendNext1.toStringAsFixed(1)}%.',
          iconName: 'query_stats_rounded',
          severity: 'normal',
          subjectName: lowestSub.subjectName,
        ),
      );
    }

    // ── 5. Subject Analysis ──────────────────────────────────────────────────
    if (highestSub != null && lowestSub != null) {
      final highPct = calculatePercentage(
        highestSub.attendedClasses,
        highestSub.totalClasses,
      );
      final lowPct = calculatePercentage(
        lowestSub.attendedClasses,
        lowestSub.totalClasses,
      );

      cards.add(
        SmartInsightCard(
          id: 'analysis_high_low',
          category: InsightCategory.subjectAnalysis,
          question: 'Which subjects have the highest and lowest attendance?',
          answer: 'Highest: ${highestSub.subjectName} at ${highPct.toStringAsFixed(1)}% (${highestSub.attendedClasses}/${highestSub.totalClasses} attended).\nLowest: ${lowestSub.subjectName} at ${lowPct.toStringAsFixed(1)}% (${lowestSub.attendedClasses}/${lowestSub.totalClasses} attended).',
          iconName: 'compare_arrows_rounded',
          severity: 'normal',
        ),
      );
    }

    // ── 6. Streaks & Performance Summary ─────────────────────────────────────
    String performanceRating = 'Excellent';
    String perfDesc = 'You are consistently maintaining attendance well above all academic thresholds.';
    if (overallPct < 60.0) {
      performanceRating = 'Critical';
      perfDesc = 'Immediate intervention required. Risk of semester debarment in multiple courses.';
    } else if (overallPct < targetPct) {
      performanceRating = 'Needs Improvement';
      perfDesc = 'Attendance is below your safety goal. Follow the recovery path to secure eligibility.';
    } else if (overallPct < 85.0) {
      performanceRating = 'Good';
      perfDesc = 'Attendance is safe and compliant. Maintain this pace through the semester.';
    }

    cards.add(
      SmartInsightCard(
        id: 'performance_summary',
        category: InsightCategory.streaks,
        question: 'Overall Performance Summary: $performanceRating',
        answer: '$perfDesc Overall attendance stands at ${overallPct.toStringAsFixed(1)}% across $totalHeld total lectures held ($totalAttended attended, $totalMissed missed).',
        iconName: 'speed_rounded',
        severity: overallPct < targetPct ? 'warning' : 'success',
      ),
    );

    return AttendanceAnalysisReport(
      overallPercentage: overallPct,
      totalHeld: totalHeld,
      totalAttended: totalAttended,
      totalMissed: totalMissed,
      targetPercentage: targetPct,
      isOverallSafe: isOverallSafe,
      totalSafeBunks: totalSafeBunks,
      totalClassesToRecover: totalRecoverNeeded,
      highestSubject: highestSub,
      lowestSubject: lowestSub,
      subjectsBelowTarget: subjectsBelow,
      subjectsAboveTarget: subjectsAbove,
      cards: cards,
    );
  }
}
