// File generated by FlutterFire CLI & updated for Web/Android support.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNWrYf9TYTdnjJX-KOPpxYyWjcV4nOiiU',
    appId: '1:127188603534:web:e7f3524f5afa46689fefdf',
    messagingSenderId: '127188603534',
    projectId: 'scholarsync-app-2026',
    authDomain: 'scholarsync-app-2026.firebaseapp.com',
    storageBucket: 'scholarsync-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDweFngNt4E28KyR976neeIMyxPQz6a5ys',
    appId: '1:127188603534:android:534bc42b183440189fefdf',
    messagingSenderId: '127188603534',
    projectId: 'scholarsync-app-2026',
    storageBucket: 'scholarsync-app-2026.firebasestorage.app',
  );
}
